spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

info:
  app:
    name: '@project.name@'
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
